spring:
  application:
    name: redesolidaria

  # SUPABASE (NUVEM)

  datasource:
    #jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      "[hibernate.format_sql]": true

  # SQLITE (LOCAL)

  # datasource:
  #   # Cria o arquivo dados.db localmente na raiz do projeto
  #   url: jdbc:sqlite:dados.db
  #   driver-class-name: org.sqlite.JDBC
  #   username: sa
  #   password: 
  # jpa:
  #   # Define o dialeto correto para o SQLite interpretar os comandos do Hibernate
  #   database-platform: org.hibernate.community.dialect.SQLiteDialect
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  #   properties:
  #     "[hibernate.format_sql]": true

jwt:
  expiration: ${JWT_EXPIRATION:86400000} #24 horas
  key: ${JWT_KEY:p!YKo=abwNKvsRQsh7q-V-mXTIqvPY8RH5r_Xw&L$k41xDM2cuVK7D41AvTUEO4qB8&lRJ7GS3v7X#0tkWV0-hrEuI7K=dUWS6-L_hoJ0PCI!LAW$Yc45=kY-jocd4ERN=T!FCc_uLyuaP2wbCGnRjpMqdWYYcEooVQpr3rvJ8Uf!m2z7g!5Xb3oydkNkS0m#&Wjoo4SxZrGVhlAF3uLPoJQ$-WTEooJ#i_Yt9aGHcudnJs79!1$jHvdrJzQJvA&$dyzzrkPr_X=IBaH#C5y9bFw1f9&E4BRDU$7Tht8VVBC4ccbmr!SQMRB87iS&u0B_z9==Y7lpEKV25a!ECJ3PnPW}